#!/usr/bin/env python3
"""Write the split fingerprint to `results/split_hash.txt` (task T6).

T6 asked for `common/split.py` to be built once, for its index hash to be written
to `results/split_hash.txt`, and for an assertion helper -- "this turns C2 from a
promise into a check". The module and the helper
(`common.results.assert_split_hash`, called by `TQNet/run.py` on every ETTh1 run)
have existed since Stage 1. The artefact never got written, so the fingerprint the
whole project asserts against was only ever visible by importing Python.

This writes it. One line per horizon, plus the inputs the hash is computed from, so
a reader can see *what* is being fingerprinted rather than just the digest. The
hash is `sha256(canonical_json(describe(...) + data_sha256))[:16]`; see
`common/split.py`.

Deliberately not a new source of truth: `common/split.py` computes the hashes and
`TQNet/run.py` holds the table it asserts against. This file is a *report* of both,
and it fails loudly if they disagree.

Re-running against an unchanged CSV reproduces this file byte-for-byte.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from common import data as data_mod  # noqa: E402
from common import split as split_mod  # noqa: E402

OUT_PATH = REPO_ROOT / "results" / "split_hash.txt"
SEQ_LEN = 96
PRED_LENS = (96, 192, 336, 720)

# Transcribed from TQNet/run.py's _ETTH1_SPLIT_HASH_BY_PRED_LEN. Duplicated here on
# purpose: if the two ever disagree, this script stops rather than publishing a
# fingerprint the runs do not actually assert.
ASSERTED_BY_RUN_PY = {
    96: "b66ee6b47e2b2eb8",
    192: "5b9f41f467356285",
    336: "a5bcaa4090739908",
    720: "17f9f51a6d81e0a2",
}


def main() -> None:
    csv_path = Path(data_mod.DEFAULT_CSV)
    if not csv_path.is_file():
        raise SystemExit(
            "{} is missing. Run `python3 tools/get_data.py` first -- the fingerprint "
            "is a function of the CSV bytes and cannot be written without them.".format(csv_path)
        )

    digest = data_mod.data_sha256(str(csv_path))

    lines = [
        "# Split fingerprint -- ETTh1, chronological 12/4/4 months (task T6)",
        "#",
        "# Generated by tools/split_fingerprint.py. Do not edit by hand.",
        "# Enforcement lives in common/results.assert_split_hash, which TQNet/run.py calls",
        "# on every ETTh1 run; this file is the human-readable record of what it asserts.",
        "#",
        "# hash = sha256(canonical_json(common.split.describe(seq_len, pred_len)",
        "#                              + {'data_sha256': <below>}))[:16]",
        "",
        "dataset      ETTh1",
        "csv          {}".format(csv_path.relative_to(REPO_ROOT)),
        "data_sha256  {}".format(digest),
        "seq_len      {}".format(SEQ_LEN),
        "stride       1",
        "",
    ]

    borders = split_mod.borders(SEQ_LEN)
    lines.append("# Row borders, half-open [start, stop), identical at every horizon")
    for name in ("train", "val", "test"):
        start, stop = borders[name]
        lines.append("border_{:<5} [{}, {})".format(name, start, stop))
    lines.append("")

    lines.append("# pred_len  split_hash        train/val/test windows")
    mismatches = []
    for pred_len in PRED_LENS:
        computed = split_mod.split_hash(SEQ_LEN, pred_len, digest)
        expected = ASSERTED_BY_RUN_PY.get(pred_len)
        if computed != expected:
            mismatches.append((pred_len, computed, expected))
        counts = split_mod.n_windows(SEQ_LEN, pred_len)
        lines.append("{:<10} {}  {} / {} / {}".format(
            pred_len, computed, counts["train"], counts["val"], counts["test"]))

    if mismatches:
        detail = "; ".join(
            "H={}: computed {} but TQNet/run.py asserts {}".format(h, c, e)
            for h, c, e in mismatches
        )
        raise SystemExit(
            "REFUSING TO WRITE: the computed fingerprint disagrees with what the runs "
            "assert -- {}. Either the CSV is not the pinned one or the split definition "
            "changed; both invalidate every committed result.".format(detail)
        )

    lines.append("")
    lines.append("# All four agree with TQNet/run.py's asserted table (checked when this was written).")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote {}".format(OUT_PATH.relative_to(REPO_ROOT)))


if __name__ == "__main__":
    main()
